parameters:
    problematic.acl_manager.class: Problematic\AclManagerBundle\Domain\AclManager

services:
    problematic.acl_manager:
        class: "%problematic.acl_manager.class%"
        arguments: ["@security.acl.dbal.provider","@security.token_storage", "@security.authorization_checker","@security.acl.object_identity_retrieval_strategy"]
