parameters:
    problematic.acl_manager.class: Problematic\AclManagerBundle\Domain\AclManager

services:
    problematic.acl_manager:
        class: %problematic.acl_manager.class%
        arguments:
            aclProvider: "@security.acl.provider"
            tokenStorage: "@security.token_storage"
            objectIdentityRetrievalStrategy: "@security.acl.object_identity_retrieval_strategy"
